export const khmerLabels: Record<string, string> = {
  person: "មនុស្ស",
  chair: "កៅអី",
  cup: "ពែង",
  bottle: "ដប",
  laptop: "កុំព្យូទ័រ",
  "cell phone": "ទូរស័ព្ទ",
  book: "សៀវភៅ",
  tv: "ទូរទស្សន៍",
  mouse: "កណ្តុរ",
  car: "រថយន្ត",
  bicycle: "កង់",
  motorcycle: "ម៉ូតូ",
  bus: "ឡានក្រុង",
  truck: "រថយន្តដឹកទំនិញ",
  cat: "ឆ្មា",
  dog: "ឆ្កែ",
  bird: "សត្វបក្សី",
  cow: "គោ",
  elephant: "ដំរី",
  horse: "សេះ",
  sheep: "ចៀម",
  bear: "ខ្លាឃ្មុំ",
  banana: "ចេក",
  apple: "ប៉ោម",
  orange: "ក្រូច",
  pizza: "ភីហ្សា",
  cake: "នំ",
  sandwich: "សាំងវិច",
  carrot: "ការ៉ុត",
  broccoli: "ប្រូខូលី",
  "hot dog": "សាច់ក្រក",
  fork: "សម",
  knife: "កាំបិត",
  spoon: "ស្លាបព្រា",
  bowl: "ចាន",
  bed: "គ្រែ",
  couch: "សាឡុង",
  toilet: "បង្គន់",
  sink: "ឡាបូ",
  refrigerator: "ទូទឹកកក",
  microwave: "ម៉ាស៊ីនកំដៅ",
  oven: "ឡដុត",
  toaster: "ម៉ាស៊ីនដុតនំប៉័ង",
  clock: "នាឡិកា",
  vase: "ថូផ្កា",
  scissors: "កន្ត្រៃ",
  backpack: "កាបូបស្ពាយ",
  handbag: "កាបូបយួរ",
  umbrella: "ឆ័ត្រ",
  tie: "ក្រវាត់ក",
  suitcase: "វ៉ាលីស",
  bench: "កៅអីវែង",
  table: "តុ",
  "dining table": "តុបាយ",
  "potted plant": "ផើងផ្កា",
  "stop sign": "សញ្ញាឈប់",
  "traffic light": "ភ្លើងស្តុប",
  "fire hydrant": "ក្បាលរ៉ូប៊ីណេពន្លត់អគ្គិភ័យ",
  "parking meter": "ម៉ាស៊ីនបង់ប្រាក់ចំណត",
  "sports ball": "បាល់",
  kite: "ខ្លែង",
  skateboard: "ស្គីបត",
  surfboard: "ក្តារស្គីទឹក",
  skis: "ស្គីទឹកកក",
  snowboard: "ស្នូប៊ត",
  "tennis racket": "រ៉ាកែតតេន្នីស",
  "baseball bat": "ដំបងបេស្បល",
  "baseball glove": "ស្រោមដៃបេស្បល",
  frisbee: "ចានហោះ",
  "wine glass": "កែវស្រា",
  airplane: "យន្តហោះ",
  train: "រថភ្លើង",
  boat: "ទូក",
  zebra: "សេះបង្កង់",
  giraffe: "សត្វកវែង",
  "teddy bear": "តុក្កតាខ្លាឃ្មុំ",
  "hair drier": "ម៉ាស៊ីនផ្លុំសក់",
  toothbrush: "ច្រាសដុសធ្មេញ",
  remote: "តេឡេ",
}